name: Integration Test Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/elgohr/publish-docker-github-action/publish-docker-github-action
        username: ${{ github.actor }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}
        registry: docker.pkg.github.com